### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by JALALDATA** [autodistill/autodistill-grounded-sam#1]
![image](https://github.com/autodistill/autodistill-grounded-sam/assets/101464720/aa1abb50-f68c-4ce9-9552-f3f92e29f6f9)

**Comment by tahereT** [comment]
I have the same error

**Comment by ghost** [comment]
<img width="830" alt="Screenshot 2023-08-06 at 17 36 12" src="https://github.com/autodistill/autodistill-grounded-sam/assets/89459321/c4679da7-d4f2-407d-baad-a9bacacd3e29">


Same

**Comment by Alisa-de** [comment]
the reason is the download process is interrupted, manually download the model checkpoints and put them in the 
~/.cache/autodistill/groundingdino/
~/.cache/autodistill/segment_anything/
folder solve this issue.

links for the models:
https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth
https://github.com/facebookresearch/segment-anything

**Comment by capjamesg** [comment]
Hello everyone! @Alisa-de is right. We have now documented this in https://github.com/autodistill/autodistill?tab=readme-ov-file#frequently-asked-questions- since it has come up so often. If @Alisa-de's solution doesn't work, please re-open this issue and I can provide further assistance.
